# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 1.0
default_acceleration_scaling_factor: 1.0

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  left_vacuum_up_joint:
    has_velocity_limits: true
    max_velocity: 0.1
    has_acceleration_limits: true
    max_acceleration: 1.8
  left_vacuum_down_joint:
    has_velocity_limits: true
    max_velocity: 0.1
    has_acceleration_limits: true
    max_acceleration: 1.8
  left_finger1_joint:
    has_velocity_limits: true
    max_velocity: 0.1
    has_acceleration_limits: true
    max_acceleration: 1.8
  left_finger2_joint:
    has_velocity_limits: true
    max_velocity: 0.1
    has_acceleration_limits: true
    max_acceleration: 1.8
  left_joint_1:
    has_velocity_limits: true
    max_velocity: 3.1415929999999999
    has_acceleration_limits: true
    max_acceleration: 3.1415929999999999
  left_joint_2:
    has_velocity_limits: true
    max_velocity: 0.76
    has_acceleration_limits: true
    max_acceleration: 0.76
  left_joint_3:
    has_velocity_limits: true
    max_velocity: 0.76
    has_acceleration_limits: true
    max_acceleration: 0.76
  left_joint_4:
    has_velocity_limits: true
    max_velocity: 3.1415929999999999
    has_acceleration_limits: true
    max_acceleration: 3.1415929999999999
  left_joint_5:
    has_velocity_limits: true
    max_velocity: 0.76
    has_acceleration_limits: true
    max_acceleration: 0.76
  left_joint_6:
    has_velocity_limits: true
    max_velocity: 3.1415929999999999
    has_acceleration_limits: true
    max_acceleration: 3.1415929999999999

  right_vacuum_up_joint:
    has_velocity_limits: true
    max_velocity: 0.1
    has_acceleration_limits: true
    max_acceleration: 1.8
  right_vacuum_down_joint:
    has_velocity_limits: true
    max_velocity: 0.1
    has_acceleration_limits: true
    max_acceleration: 1.8
  right_finger1_joint:
    has_velocity_limits: true
    max_velocity: 0.1
    has_acceleration_limits: true
    max_acceleration: 1.8
  right_finger2_joint:
    has_velocity_limits: true
    max_velocity: 0.1
    has_acceleration_limits: true
    max_acceleration: 1.8
  right_joint_1:
    has_velocity_limits: true
    max_velocity: 3.1415929999999999
    has_acceleration_limits: true
    max_acceleration: 3.1415929999999999
  right_joint_2:
    has_velocity_limits: true
    max_velocity: 0.76
    has_acceleration_limits: true
    max_acceleration: 0.76
  right_joint_3:
    has_velocity_limits: true
    max_velocity: 0.76
    has_acceleration_limits: true
    max_acceleration: 0.76
  right_joint_4:
    has_velocity_limits: true
    max_velocity: 3.1415929999999999
    has_acceleration_limits: true
    max_acceleration: 3.1415929999999999
  right_joint_5:
    has_velocity_limits: true
    max_velocity: 0.76
    has_acceleration_limits: true
    max_acceleration: 0.76
  right_joint_6:
    has_velocity_limits: true
    max_velocity: 3.1415929999999999
    has_acceleration_limits: true
    max_acceleration: 3.1415929999999999